sudo: required
services:
  - docker
before_install:
  -  docker build -t harisht847/react-test -f ./client/Dockerfile.dev ./client  

script:
  - docker build -t harisht847/multi-client ./client
  - docker build -t harisht847/multi-ngnix ./nginx
  - docker build -t harisht847/multi-server ./server
  - docker build -t harisht847/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push harisht847/multi-client
  - docker push harisht847/multi-nginx
  - docker push harisht847/multi-server
  - docker push harisht847/multi-worker
